stages:
  - dependencies
  - prepare
  - build
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'

default:
  tags:
    - 'mais'
  image: node:23

cache:
  key: node_modules
  paths:
    - node_modules/

dependencies:
  stage: dependencies
  before_script:
    - echo "Install dependencies..."
  script:
    - npm install -g pnpm
    - npm install -g nuxi
    - pnpm i

prepare:
  stage: prepare
  dependencies:
    - dependencies
  before_script:
    - echo "Prepare for build..."
  script:
    - npm install -g pnpm
    - npm install -g nuxi
    - pnpm run postinstall
  artifacts:
    paths:
      - .nuxt/
    expire_in: 1 hour

build:
  stage: build
  dependencies:
    - prepare
  before_script:
    - echo "Building..."
  script:
    - npm install -g pnpm
    - npm install -g nuxi
    - pnpm run build
  artifacts:
    paths:
      - .nuxt/
      - .output/
      - config/
      - i18n/
    expire_in: 1 hour

deploy-mais:
  stage: deploy
  image: docker:latest
  tags:
    - 'mais'
  dependencies:
    - build
  before_script:
    - echo "Deploying to mais..."
    - export PORT=4440
    - export DATABASE_NAME="$DATABASE_NAME"
    - export DATABASE_URL="$DATABASE_URL"
    - export DOMAIN="$DOMAIN"
    - export AUTH_DOMAIN="$AUTH_DOMAIN"
    - export S3_ENDPOINT="$S3_ENDPOINT"
    - export S3_REGION="$S3_REGION"
    - export S3_ACCESS_KEY="$S3_ACCESS_KEY"
    - export S3_SECRET_KEY="$S3_SECRET_KEY"
    - export S3_BUCKET="$S3_BUCKET"
  script:
    - docker compose up --detach --build

deploy-res-6:
  stage: deploy
  image: docker:latest
  tags:
    - 'res-6'
  dependencies:
    - build
  before_script:
    - echo "Deploying to helios..."
    - export PORT=4440
    - export DATABASE_NAME="$DATABASE_NAME"
    - export DATABASE_URL="$DATABASE_URL"
    - export DOMAIN="$DOMAIN"
    - export AUTH_DOMAIN="$AUTH_DOMAIN"
    - export S3_ENDPOINT="$S3_ENDPOINT"
    - export S3_REGION="$S3_REGION"
    - export S3_ACCESS_KEY="$S3_ACCESS_KEY"
    - export S3_SECRET_KEY="$S3_SECRET_KEY"
    - export S3_BUCKET="$S3_BUCKET"
  script:
    - docker compose up --detach --build
