export default {
  inventory: [
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
    { item: 'AIR', amount: 0 },
  ],
};
