export default {
  button_login: 'pixelarticons:login',
  button_logout: 'pixelarticons:logout',
  nav_home: 'pixelarticons:home',
  nav_map: 'pixelarticons:map',
  nav_shop: 'pixelarticons:store',
  nav_servers: 'pixelarticons:server',
  nav_faq: 'pixel:question',
  nav_theme_system: 'pixelarticons:monitor',
  nav_theme_dark: 'pixelarticons:moon-star',
  nav_theme_light: 'pixelarticons:sun-alt',
  nav_lang: 'pixel:globe-americas',
  shop_cart: 'pixelarticons:cart',
  arrow_left: 'pixelarticons:arrow-left',
  arrow_right: 'pixelarticons:arrow-right',
  dollar: 'pixelarticons:dollar',
  clear: 'pixelarticons:trash',
  plus: 'pixelarticons:plus',
  account: 'pixelarticons:user',
  settings: 'pixelarticons:list',
  gold: 'mdi:gold',
  accept: 'pixelarticons:check',
  info: 'pixelarticons:info-box',
  home: 'pixelarticons:home',
};
